import { NgModule } from '@angular/core';
import {
        MatButtonModule,
        MatIconModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatSelectModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule,
        MatSnackBarModule,
        MatProgressBarModule,
        MatSlideToggleModule,
        MatSliderModule,
        MatExpansionModule,
        MatDividerModule,
        MatRadioModule
    } from '@angular/material';



 @NgModule({
 imports: [ MatButtonModule,
           MatIconModule,
           MatFormFieldModule,
           MatInputModule,
           MatDatepickerModule,
           MatNativeDateModule,
           MatCheckboxModule,
           MatSidenavModule,
           MatToolbarModule,
           MatListModule,
           MatTabsModule,
           MatCardModule,
           MatSelectModule,
           MatProgressSpinnerModule,
           MatDialogModule,
           MatTableModule,
           MatSortModule,
           MatPaginatorModule,
           MatSnackBarModule,
           MatProgressBarModule,
           MatSlideToggleModule,
           MatSliderModule,
           MatExpansionModule,
           MatDividerModule,
           MatRadioModule
        ],
 exports: [ MatButtonModule,
            MatIconModule,
            MatFormFieldModule,
            MatInputModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatCheckboxModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatTabsModule,
            MatCardModule,
            MatSelectModule,
            MatProgressSpinnerModule,
            MatDialogModule,
            MatTableModule,
            MatSortModule,
            MatPaginatorModule,
            MatSnackBarModule,
            MatProgressBarModule,
            MatSlideToggleModule,
            MatSliderModule,
            MatExpansionModule,
            MatDividerModule,
            MatRadioModule
        ]
})
export class MaterialModule {}
